<?php
		include_once "functii.php";
		connect(onc);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id AND participanti.judet='".$_GET[jud]."'";
		$result=mysql_query($query);
		$tot=mysql_num_rows($result);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id  AND participanti.judet='".$_GET[jud]."' AND rezultate.total<=100 AND rezultate.total>=90";
		$result=mysql_query($query);
		$unu=mysql_num_rows($result);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id  AND participanti.judet='".$_GET[jud]."' AND rezultate.total<90 AND rezultate.total>=80";
		$result=mysql_query($query);
		$doi=mysql_num_rows($result);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id  AND participanti.judet='".$_GET[jud]."' AND rezultate.total<80 AND rezultate.total>=70";
		$result=mysql_query($query);
		$trei=mysql_num_rows($result);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id  AND participanti.judet='".$_GET[jud]."' AND rezultate.total<70 AND rezultate.total>=60";
		$result=mysql_query($query);
		$patru=mysql_num_rows($result);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id  AND participanti.judet='".$_GET[jud]."' AND rezultate.total<60 AND rezultate.total>=50";
		$result=mysql_query($query);
		$cinci=mysql_num_rows($result);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id  AND participanti.judet='".$_GET[jud]."' AND rezultate.total<50 AND rezultate.total>=40";
		$result=mysql_query($query);
		$sase=mysql_num_rows($result);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id  AND participanti.judet='".$_GET[jud]."' AND rezultate.total<40 AND rezultate.total>=30";
		$result=mysql_query($query);
		$sapte=mysql_num_rows($result);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id  AND participanti.judet='".$_GET[jud]."' AND rezultate.total<30 AND rezultate.total>=20";
		$result=mysql_query($query);
		$opt=mysql_num_rows($result);
		$query="SELECT * FROM rezultate,participanti WHERE rezultate.id_elev=participanti.id  AND participanti.judet='".$_GET[jud]."' AND rezultate.total<20 AND rezultate.total>=10";
		$result=mysql_query($query);
		$noua=mysql_num_rows($result);
		$inaltime=140;
        $latime=600;
        $img=imagecreate($latime,$inaltime);
		$culoare=imagecolorallocate($img,255,255,255);
		$culoarecerc2=imagecolorallocate($img,0,151,75);
		$culoarecerc4=imagecolorallocate($img,200,0,0);
		$x1=30;
		$y1=100;
		$x2=40;
		$y2=100-(100*$unu/$tot);
		imagefilledrectangle($img, $x1, $y1, $x2, $y2, $culoarecerc4);
		imagestring ($img, 4, $x1-20, 110,'100-90', $culoarecerc2);
		$x1+=50;
		$x2+=50;
		$y2=100-(100*$doi/$tot);
		imagefilledrectangle($img, $x1, $y1, $x2, $y2, $culoarecerc4);
		imagestring ($img, 4, $x1-15, 110,'90-80', $culoarecerc2);
		$x1+=50;
		$x2+=50;
		$y2=100-(100*$trei/$tot);
		imagefilledrectangle($img, $x1, $y1, $x2, $y2, $culoarecerc4);
		imagestring ($img, 4, $x1-15, 110,'80-70', $culoarecerc2);
		$x1+=50;
		$x2+=50;
		$y2=100-(100*$patru/$tot);
		imagefilledrectangle($img, $x1, $y1, $x2, $y2, $culoarecerc4);
		imagestring ($img, 4, $x1-15, 110,'70-60', $culoarecerc2);
		$x1+=50;
		$x2+=50;
		$y2=100-(100*$patru/$tot);
		imagefilledrectangle($img, $x1, $y1, $x2, $y2, $culoarecerc4);
		imagestring ($img, 4, $x1-15, 110,'60-50', $culoarecerc2);
		$x1+=50;
		$x2+=50;
		$y2=100-(100*$patru/$tot);
		imagefilledrectangle($img, $x1, $y1, $x2, $y2, $culoarecerc4);
		imagestring ($img, 4, $x1-15, 110,'50-40', $culoarecerc2);
		$x1+=50;
		$x2+=50;
		$y2=100-(100*$patru/$tot);
		imagefilledrectangle($img, $x1, $y1, $x2, $y2, $culoarecerc4);
		imagestring ($img, 4, $x1-15, 110,'40-30', $culoarecerc2);
		$x1+=50;
		$x2+=50;
		$y2=100-(100*$patru/$tot);
		imagefilledrectangle($img, $x1, $y1, $x2, $y2, $culoarecerc4);
		imagestring ($img, 4, $x1-15, 110,'30-20', $culoarecerc2);
		$x1+=50;
		$x2+=50;
		$y2=100-(100*($tot-($unu+$doi+$trei+$mentiune))/$tot);
		imagefilledrectangle($img, $x1, $y1, $x2, $y2, $culoarecerc4);
		imagestring ($img, 4, $x1-15, 110,'20-10', $culoarecerc2);
		header("Content-type: image/jpeg");
         		imagejpeg($img);
         		imagedestroy($img);
?>
